### ISSUE TITLE
``loadspreadsheet`` should not create empty folder structure?

### ISSUE THREAD

**Issue by kelvinburke** [sciris/sciris#515] opened 2023-08-08 06:01 UTC
Hi @cliffckerr !
If the folder associated with a ``filename`` doesn't exist, currently ``loadspreadsheet`` will create the folder structure when calling ``makefilepath``. Then later an error will be thrown trying to read the non-existent spreadsheet from the new empty folder.

This is not really an issue, but to me it seems more logical that ``loadspreadsheet`` calls ``makefilepath`` with ``makedirs=False`` as loading a spreadsheet seems like a read-only operation.

Optionally, we could call ``makefilepath`` with ``makedirs=False, checkexists=True``, depending on if you want the error to be thrown right away or not.

**Comment by kelvinburke** [comment] 2023-08-08 06:07
The same thing happens in ``Blobject.load.read_file``

**Comment by cliffckerr** [comment] 2023-08-08 10:47
Thanks for finding this @kelvinburke, I agree! I'll include this in the upcoming 3.1.0 release (which was supposed to be 3.0.1 but kept growing :joy:)

**Comment by cliffckerr** [comment] 2023-08-09 22:53
@kelvinburke Could you check what version of Sciris you're using? I'm not able to reproduce locally, and it looks like this was fixed in version 3.0.0:
https://sciris.readthedocs.io/en/latest/whatsnew.html#files
Going to close for now but please reopen if you're still encountering it!

**Closed by cliffckerr** 2023-08-09 22:53 UTC
Labels: bug

**Comment by kelvinburke** [comment] 2023-08-09 23:06
Yup my mistake, I was on 2.x
